
CREATE TABLE Customers(
	CustomerId INT IDENTITY(1,1) NOT NULL,
	FirstName NVARCHAR(255) NOT NULL,
	LastName NVARCHAR(255) NOT NULL,
	PRIMARY KEY(CustomerId)
);

CREATE TABLE Orders(
	OrderId INT IDENTITY(1,1) NOT NULL,
	OrderDate DATETIME2 DEFAULT SYSUTCDATETIME(),
	Amount INT DEFAULT 1 CHECK(Amount > 0),
	TotalCost MONEY NOT NULL CHECK(TotalCost > 0),
	CustomerId INT NOT NULL
	PRIMARY KEY(OrderId)
	CONSTRAINT FK_Orders_CustomerId FOREIGN KEY(CustomerId) REFERENCES Customers (CustomerId) ON DELETE CASCADE
);

CREATE TABLE Stores(
	StoreId INT IDENTITY(1,1) NOT NULL,
	OrderId INT NOT NULL,
	StoreName NVARCHAR(255) NOT NULL,
	PRIMARY KEY(StoreId),
	CONSTRAINT FK_Stores_OrderId FOREIGN KEY(OrderId) REFERENCES Orders (OrderId)
);

CREATE TABLE Products(
	ProductId UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	ProductName NVARCHAR(255) NOT NULL,
	Price MONEY NOT NULL CHECK(Price > 0),
	PRIMARY KEY(ProductId)
);

CREATE TABLE ProductsOfOrders(
	OrderId INT NOT NULL,
	ProductId UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT PK_ProductsOfOrder_OrderId_ProductId PRIMARY KEY(OrderId, ProductId),
	CONSTRAINT FK_PofO_Products_ProductId FOREIGN KEY(ProductId) REFERENCES Products (ProductId) ON DELETE CASCADE,
	CONSTRAINT FK_PofO_Orders_OrderId FOREIGN KEY(OrderId) REFERENCES Orders (OrderId) ON DELETE CASCADE
);

CREATE TABLE ProductsInStores(
	StoreId INT NOT NULL,
	ProductId UNIQUEIDENTIFIER NOT NULL,
	Inventory INT NOT NULL CHECK(Inventory > 0),
	CONSTRAINT PK_ProductsInStores_StoreId_ProductId PRIMARY KEY(StoreId, ProductId),
	CONSTRAINT FK_PinS_Stores_StoreId FOREIGN KEY(StoreId) REFERENCES Stores (StoreId) ON DELETE CASCADE,
	CONSTRAINT FK_PinS_Products_ProductId FOREIGN KEY(ProductId) REFERENCES Products (ProductId) ON DELETE CASCADE
);

--DROP TABLE Customers
--DROP TABLE Orders
--DROP TABLE Stores
--DROP TABLE Products
--DROP TABLE ProductsOfOrders
--DROP TABLE ProductsInStores
